# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`PerlX-Maybe-XS`
	:runtime-requirement    [ :on "perl 5.008"^^:CpanId ];
	:runtime-recommendation [ :on "PerlX::Maybe"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.61"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

